StartupEvents.registry('item', event => {
  event.create('ancient_slate').displayName('古代石板').maxStackSize(1).rarity('EPIC')
  event.create('trial_crest').displayName('试炼之证').maxStackSize(16).rarity('RARE')
  event.create('goddess_token').displayName('女神祈愿徽记').maxStackSize(1).rarity('EPIC')
  event.create('rune_bomb').displayName('爆破符文').maxStackSize(1).rarity('EPIC')
  event.create('rune_stasis').displayName('静滞符文').maxStackSize(1).rarity('EPIC')
  event.create('rune_cryonis').displayName('冰柱符文').maxStackSize(1).rarity('EPIC')
  event.create('rune_magnesis').displayName('磁力符文').maxStackSize(1).rarity('EPIC')
  event.create('korok_seed').displayName('森灵种子').maxStackSize(64).rarity('RARE')
  event.create('tower_sigil').displayName('塔之认证').maxStackSize(16).rarity('RARE')
  event.create('champion_sigil_wind').displayName('风之英杰徽记').maxStackSize(1).rarity('EPIC')
  event.create('champion_sigil_water').displayName('水之英杰徽记').maxStackSize(1).rarity('EPIC')
  event.create('champion_sigil_fire').displayName('火之英杰徽记').maxStackSize(1).rarity('EPIC')
  event.create('champion_sigil_desert').displayName('雷沙英杰徽记').maxStackSize(1).rarity('EPIC')
})

StartupEvents.registry('block', event => {
  event.create('shrine_terminal').displayName('古代试炼终端').hardness(4.0).resistance(1200.0).lightLevel(0.72)
  event.create('tower_terminal').displayName('区域塔终端').hardness(5.0).resistance(1200.0).lightLevel(0.85)
  event.create('korok_pedestal').displayName('森灵谜题基座').hardness(2.5).resistance(30.0).lightLevel(0.28)
  event.create('dungeon_terminal_wind').displayName('风之神兽控制终端').hardness(5.0).resistance(1200.0).lightLevel(0.80)
  event.create('dungeon_terminal_water').displayName('水之神兽控制终端').hardness(5.0).resistance(1200.0).lightLevel(0.80)
  event.create('dungeon_terminal_fire').displayName('火之神兽控制终端').hardness(5.0).resistance(1200.0).lightLevel(0.80)
  event.create('dungeon_terminal_desert').displayName('雷沙神兽控制终端').hardness(5.0).resistance(1200.0).lightLevel(0.80)
  event.create('boss_altar_wind').displayName('风之灾厄祭坛').hardness(6.0).resistance(1200.0).lightLevel(0.55)
  event.create('boss_altar_water').displayName('水之灾厄祭坛').hardness(6.0).resistance(1200.0).lightLevel(0.55)
  event.create('boss_altar_fire').displayName('火之灾厄祭坛').hardness(6.0).resistance(1200.0).lightLevel(0.55)
  event.create('boss_altar_desert').displayName('雷沙灾厄祭坛').hardness(6.0).resistance(1200.0).lightLevel(0.55)
})
